---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validate-Struct
no_index:
  directory:
    - t
    - inc
requires:
  Data::Validate: 0.06
  Data::Validate::IP: 0.18
  Regexp::Common: 0
resources:
  repository: https://github.com/TLINDEN/Data-Validate-Struct
version: 0.08
